apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysqlpv-production
   labels:
     app: wordpress
     tier: mysql
spec:
  storageClassName: mysqlpv-production 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/production/mysql
    server: k8sstorageaccountcem.file.core.windows.net

