apiVersion: v1
kind: PersistentVolume
metadata:
   name: wordpresspv-production
   labels:
     app: wordpress
spec:
  storageClassName: wordpresspv-production
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/production/wordpress
    server: k8sstorageaccountcem.file.core.windows.net
