apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-test
spec:
  rules:
    - host: testblog.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
