secretGenerator:
- name: mysql-pass
  literals:
  - password=test123
namespace: test
resources:
  - mysql-test-deployment.yaml
  - mysql-test-pv.yaml
  - wordpress-test-deployment.yaml
  - wordpress-test-pv.yaml
  - ingress.yaml
