apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysqlpv
   namespace: test
   labels:
     app: wordpress
     tier: mysql
spec:
  storageClassName: mysqlpv-test 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/test/wordpress-mysql
    server: k8sstorageaccountcem.file.core.windows.net
