apiVersion: v1
kind: PersistentVolume
metadata:
   name: wordpresspv
   namespace: test
   labels:
     app: wordpress
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/test/wordpress
    server: k8sstorageaccountcem.file.core.windows.net
