apiVersion: v1
kind: PersistentVolume
metadata:
   name: wordpresspv
   namespace: test
   labels:
     app: wordpress
spec:
  storageClassName: wordpresspv-test
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/
    server: k8sstorageaccountcem.file.core.windows.net
