apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozgurozturknet
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ozgurozturknet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: ozgurozturknet
    spec:
      tolerations:
      - key: "environment"
        operator: "Equal"
        value: "production"
        effect: "NoExecute"
      containers:
      - name: ozgurozturknet
        image: ozgurozturknet/k8s:v1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
    