apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
  labels:
    name: mongo
spec:
  storageClassName: mongo-pv
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/mongodb/0
    server: k8sstorageaccountcem.file.core.windows.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
  labels:
    name: mongo
spec:
  storageClassName: mongo-pv
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorageaccountcem/k8s-nfs/mongodb/1
    server: k8sstorageaccountcem.file.core.windows.net
