apiVersion: v1
kind: Pod
metadata:
  name: sapod
  namespace: default
spec:
  serviceAccountName: readonlysa
  containers:
  - name: testcontainer
    image: nicolaka/netshoot
    command: ["/bin/sh"]
    ports:
    - containerPort: 80
