apiVersion: v1
kind: Pod
metadata:
  name: sapod
  namespace: default
spec:
  serviceAccountName: readonlysa
  containers:
  - name: testcontainer
    image: ozgurozturknet/k8s:latest
    ports:
    - containerPort: 80
