apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonlysa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readonlyrole
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sareadonlyrolebinding
subjects:
- kind: ServiceAccount
  name: readonlysa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: readonlyrole
  apiGroup: rbac.authorization.k8s.io
